- name: Setup NodeJS
  tags: [js, nodejs, shell]
  block:
    - name: Install NVM
      shell: |
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
      args:
        creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"

    - name: Install Node
      shell: |
        export NVM_DIR="{{ ansible_env.HOME }}/.nvm"
        . "$NVM_DIR/nvm.sh"
        nvm install {{ item }}
      with_items:
        - 'lts/*'
        - node
      register: install_node

    - name: Set Default Node Version
      shell: |
        export NVM_DIR="{{ ansible_env.HOME }}/.nvm"
        . "$NVM_DIR/nvm.sh"
        nvm alias default 'lts/*'

    - name: Get Node Version
      shell: |
        export NVM_DIR="{{ ansible_env.HOME }}/.nvm"
        . "$NVM_DIR/nvm.sh"
        nvm version default
      register: node_version

- name: Setup Typescript
  when: node_version is succeeded
  tags: [ts, shell]
  environment:
    PATH: "{{ ansible_env.HOME }}/.nvm/versions/node/{{ node_version.stdout }}/bin:{{ ansible_env.PATH }}"
  block:
    - name: Install Typescript
      npm:
        name: "{{ item }}"
        global: yes
      with_items:
        - typescript
        - ts-node

- name: Setup Python
  tags: [python, shell]
  block:
    - name: Install Python
      package:
        name: [python3, python3-pip]
        state: present
      become: true

- name: Setup Haskell
  tags: [haskell, shell]
  block:
    - name: Install Haskell
      package:
        name: [ghc, ghc-prof, ghc-doc]
        state: present
      become: true

