- name: Install core CLI packages
  package:
    name: [curl]
    state: present
  become: true
  tags: [shell]

- name: Install main dev packages
  package:
    name: [git, neovim, gh]
    state: present
  become: true
  tags: [shell]

- name: Add apt repositories
  apt_repository:
    repo: ppa:wslutilities/wslu
  become: true
  tags: [shell]

- name: Install common CLI utils
  package:
    name: [wslu, jq, fzf, silversearcher-ag, tree]
    state: present
  become: true
  tags: [shell]


