- name: Setup WSL
  import_tasks: dev/wsl.yml
  tags: [wsl]

- name: Install VSCode
  win_winget:
    id: microsoft.visualstudiocode
  register: vscode
  tags: [application, vscode]

- name: Install VSCode Remote Dev Extensions
  win_command: code --install-extension ms-vscode-remote.vscode-remote-extensionpack
  tags: [vscode, wsl]

- name: Setup Powershell
  import_tasks: dev/powershell.yml
  tags: [powershell, terminal]

# - name: Setup Dotfiles
#   import_tasks: dev/dotfiles.yml
#   tags: [dotfiles]

- name: Manual Steps (VSCode)
  pause:
    seconds: 1
    prompt: |
      ===============
        [VSCode] Manual Steps:
        - Log in to sync the settings
      ===============
  when: vscode is success
  tags: [manual-steps]

