- name: Install Spotify
  win_winget:
    name: 'Spotify Music'
    source: msstore
  tags: [application]

- name: Install MuseScore
  tags: [musescore]
  block:
    - name: Get latest MuseScore installer
      uri:
        url: https://api.github.com/repos/musescore/musescore/releases/latest
        return_content: true
      register: musescore_latest
      tags: [application]

    - name: Install MuseScore {{ musescore_latest.json.tag_name }}
      loop: "{{ musescore_latest.json.assets }}"
      when: "'x86_64.msi' in item.name"
      win_package:
        path: "{{ item.browser_download_url }}"
        product_id: '{0A7FE0EB-6049-4FE5-8C61-122149891EAE}'
        creates_path: 'C:\Program Files\MuseScore 4'
      tags: [application]

    - name: Mention MuseHub
      pause:
        seconds: 1
        prompt: |
          ===============
            [MuseHub] Muse Hub can be installed manually here:
            https://www.musehub.com
          ===============
      tags: [manual-step]


