- name: Install PowerToys
  win_winget:
    id: microsoft.powertoys
  register: powertoys
  tags: [application]

- name: Manual Steps (PowerToys)
  pause:
    seconds: 1
    prompt: |
      ===============
        [PowerToys] Manual Steps:
        - Log in
        - Sync the settings
      ===============
  tags: [manual-step]
  when: powertoys is success

- name: Install Terminal
  win_winget:
    id: microsoft.windowsterminal
  tags: [application, terminal]

# edit terminal settings - with the dotfiles..?
# $settings = (Get-Item "C:\users\$env:UserName\AppData\Local\Packages\Microsoft.WindowsTerminal_*\LocalState\settings.json")
# $settings.DirectoryName

