- name: Setup Ansible (WSL)
  win_command: >-
    wsl -d {{ wsl_distro }} --
      sudo apt-add-repository -y ppa:ansible/ansible '&&'
      sudo apt-get update -y '&&'
      sudo apt-get install -y curl git software-properties-common ansible

- name: Run WSL Playbook
  win_shell: >-
    params=$(cat <<EOI
    {
      {% if ssh_key_filename %} "ssh_key_filename": "{{ ssh_key_filename | replace('\"', '\\\"') | safe }}", {% endif %}
      {% if ssh_key_passphrase %} "ssh_key_passphrase": "{{ ssh_key_passphrase | replace('\"', '\\\"') | safe }}", {% endif %}
      {% if gpg_key_name %} "gpg_key_name ": "{{ gpg_key_name | replace('\"', '\\\"') | safe }}", {% endif %}
      {% if gpg_key_email %} "gpg_key_email": "{{ gpg_key_email | replace('\"', '\\\"') | safe }}", {% endif %}
      {% if gpg_key_passphrase %} "gpg_key_passphrase": "{{ gpg_key_passphrase | replace('\"', '\\\"') | safe }}", {% endif %}
      "dummy": "to swallow trailing comma"
    }
    EOI
    )

    wsl -d {{ wsl_distro }} -- ansible-pull linux/wsl-playbook.yml
      --url https://github.com/tkburns/ansible.git
      --tags "{{ ansible_run_tags | join(',') }}"
      {% if wsl_playbook_tags %} --tags "{{ wsl_playbook_tags }}" {% endif %}
      -e "$params"
      {% if wsl_playbook_args %} {{ wsl_playbook_args }} {% endif %}
  check_mode: no
  register: wsl_playbook

- name: Display WSL playbook output
  pause:
    seconds: 1
    prompt: '{{ wsl_playbook.stdout }}'


