- name: Check if WSL is installed
  ansible.windows.win_powershell:
    script: |
      $env:WSL_UTF8=1
      if ( '{{ wsl_distro }}' ) {
          $distro = wsl --list | Select-String '{{ wsl_distro }}'
      } else {
          $distro = wsl --list
      }
      $Ansible.Result = $distro.Count -ne 0
  register: wsl_exists

- name: Install WSL
  win_command: wsl --install {{ wsl_distro }}
  when: not wsl_exists.result

