- name: Check if WSL is installed
  win_powershell: |
    $env:WSL_UTF8=1
    $distro = wsl --list | Select-String '{{ wsl_distro }}'
    $Ansible.Result = $distro.Count -ne 0
  register: wsl_exists

- name: Install WSL
  win_command: wsl --install {{ wsl_distro }}
  when: not wsl_exists.result

