- name: Setup Ansible (WSL)
  win_command: >-
    wsl -d {{ wsl_distro }} --
      sudo apt-add-repository -y ppa:ansible/ansible '&&'
      sudo apt-get update -y '&&'
      sudo apt-get install -y curl git software-properties-common ansible

- name: Run WSL Playbook
  win_command: >-
    wsl -d {{ wsl_distro }} -- ansible-pull linux/wsl-playbook.yml
      --url https://github.com/tkburns/ansible.git
      --tags "{{ ansible_run_tags | join(',') }}"
      {% if wsl_playbook_tags %} --tags "{{ wsl_playbook_tags }}" {% endif %}

