- hosts: localhost
  vars:
    is_wsl: true
    project_dir: ~/projects

    ssh_key_filename: id_ed25519
    # ssh_key_passphrase
    # gpg_key_name
    # gpg_key_email
    # gpg_key_passphrase

  pre_tasks:
    - name: Update Apt Cache
      become: true
      apt:
        update_cache: true
      tags: [terminal, shell]

  tasks:
    - name: Setup Terminal
      import_tasks: tasks/terminal.yml
      tags: [terminal]
    - name: Setup Langs
      import_tasks: tasks/langs.yml
      tags: [lang]
    - name: Setup Keys
      import_tasks: tasks/keys.yml
      tags: [key]
    - name: Setup Projects
      import_tasks: tasks/projects.yml
      tags: [project]

